"""Deterministic unsupported-condition detection (ARCF architecture
hardening §13) — path/marker-based heuristics only, no parsing, no
execution.

Explicitly best-effort and documented as such: these signals are not
exhaustive. A generated file that matches none of these conventions, or
reflection-heavy code that doesn't use one of these call patterns, will
go undetected — the goal is surfacing the common cases so the final LLM
package can flag them, not guaranteeing completeness (which would need
real parsing/execution this module deliberately avoids, per the
hardening brief's prohibition on runtime execution or execution
tracing).
"""

_GENERATED_PATH_MARKERS: tuple[str, ...] = ("/generated/", "/.generated/", "/__generated__/")

_GENERATED_FILENAME_SUFFIXES: tuple[str, ...] = (
    "_pb2.py",
    "_pb2_grpc.py",
    ".g.cs",
    ".g.dart",
    ".pb.go",
    ".freezed.dart",
    ".designer.cs",
)

_GENERATED_CONTENT_MARKERS: tuple[str, ...] = (
    "@generated",
    "do not edit",
    "code generated by",
    "this file is auto-generated",
    "<auto-generated",
)


def is_generated_file(relative_path: str, content: str | None = None) -> bool:
    lowered_path = relative_path.lower()
    if any(marker in lowered_path for marker in _GENERATED_PATH_MARKERS):
        return True
    if any(lowered_path.endswith(suffix) for suffix in _GENERATED_FILENAME_SUFFIXES):
        return True
    return content is not None and any(
        marker in content[:500].lower() for marker in _GENERATED_CONTENT_MARKERS
    )


_DYNAMIC_DISPATCH_MARKERS: tuple[str, ...] = (
    "getattr(",
    "setattr(",
    "importlib.import_module(",
    "@inject",
    "reflect.",
    "class.forname(",
    "activator.createinstance(",
)


def has_dynamic_dispatch_hint(content: str) -> bool:
    lowered = content.lower()
    return any(marker in lowered for marker in _DYNAMIC_DISPATCH_MARKERS)
