"""Multi-Axis Query Decomposition — ARCF experiment (2026-08-08).

Feature-flagged (code_intelligence/service.py's
`enable_multi_axis_decomposition`, default False), deterministic, no
embeddings, no SLM, no new ranking mechanism (reuses RelevanceRanker as-
is), and NOT combined with the subsystem-localization / ranked-probe /
anchor-classification experiments — those stay off on this path by
construction (service.py wires this as a separate, mutually-exclusive
branch, not a composable layer on top of the others).

Hypothesis under test: a comparative/cross-cutting query names two (or
more) distinct things and asks about their relationship. Today's
pipeline pools every candidate from the whole query into one ranked
list, where a file relevant to only ONE side of the comparison has to
outcompete noise generated by the WHOLE query combined. Splitting the
query into independent "axes" and giving each its own small, guaranteed
quota might let a file win its own axis's much smaller competition even
when it could never win the whole-query pooled one.

Decomposition mechanism, deliberately general rather than repository- or
domain-specific (the brief's own constraint): splits on a small set of
general English comparative/coordinating markers — sentence structure,
not vocabulary about loading strategies, SQL, or any other domain — the
first such marker found in the raw query text (case-insensitive) splits
it into exactly two axis sub-queries. A query with none of these markers
decomposes to a single axis (itself) — service.py's caller treats a
single-axis result as "nothing to decompose", so this flag has NO EFFECT
on non-comparative queries, by construction, not by a separate check.
"""

from dataclasses import dataclass

# General comparative/coordinating English sentence structure — applies
# to any query in any repository, never tuned to SQLAlchemy or any other
# specific codebase's vocabulary.
_AXIS_SPLIT_MARKERS: tuple[str, ...] = (
    " differs from ",
    " differ from ",
    " versus ",
    " vs. ",
    " vs ",
    " compared to ",
    " as opposed to ",
    " rather than ",
    " and what ",
    " and how ",
    " while ",
)


@dataclass(frozen=True)
class QueryAxis:
    text: str


def decompose_query(raw_request: str) -> list[QueryAxis]:
    """Splits `raw_request` into exactly two axes at the first (leftmost)
    general comparative/coordinating marker found in the text — a query
    with no such marker returns a single axis (itself, unchanged),
    signalling "nothing to decompose" to the caller."""
    lowered = raw_request.lower()
    best_index: int | None = None
    best_marker: str | None = None
    for marker in _AXIS_SPLIT_MARKERS:
        index = lowered.find(marker)
        if index != -1 and (best_index is None or index < best_index):
            best_index = index
            best_marker = marker
    if best_index is None or best_marker is None:
        return [QueryAxis(raw_request)]
    left = raw_request[:best_index].strip()
    right = raw_request[best_index + len(best_marker) :].strip()
    axes = [QueryAxis(text) for text in (left, right) if text]
    return axes if len(axes) >= 2 else [QueryAxis(raw_request)]
