from code_intelligence.unsupported_conditions import has_dynamic_dispatch_hint, is_generated_file


def test_generated_directory_path_detected() -> None:
    assert is_generated_file("api/generated/client.py") is True


def test_generated_filename_suffix_detected() -> None:
    assert is_generated_file("proto/service_pb2.py") is True
    assert is_generated_file("Models/User.g.cs") is True


def test_generated_content_marker_detected() -> None:
    assert is_generated_file("client.py", content="# @generated by tool\ndef f(): pass") is True


def test_ordinary_file_is_not_generated() -> None:
    assert is_generated_file("app/handler.py", content="def handle():\n    pass\n") is False


def test_dynamic_dispatch_hint_detected() -> None:
    assert has_dynamic_dispatch_hint("value = getattr(obj, name)") is True
    assert has_dynamic_dispatch_hint("@Inject\nprivate Service service;") is True


def test_ordinary_content_has_no_dynamic_dispatch_hint() -> None:
    assert has_dynamic_dispatch_hint("def handle():\n    return obj.method()\n") is False
